### PR TITLE
Support building RPM package for Fedora

### PR DESCRIPTION
**Pull request by jwakely**
Add elektroid.spec so that an RPM can be built.

### CODE REVIEW

**Comment by jwakely** [comment]
Pre-built RPMs are available from https://copr.fedorainfracloud.org/coprs/jwakely/elektroid/

**Comment by dagargo** [comment]
Thank you so much for working on the RPM package. This is rad!

**Comment by jwakely** [comment]
It was easy compared to your work on elektroid, so thank *you*!

**Comment by jwakely** [comment]
I should document the steps to build an RPM from the spec file. I'll make a note to do that...

**Comment by dagargo** [comment]
BTW, I've just updated the project and summary in the configuration files. Could you check it out the Fedora file? Just in case the format is wrong or something.

**Comment by jwakely** [comment]
Yep, it's fine.

To build an RPM from the spec file (using `mock` to build in a clean env):

```
rel=35
mock -r fedora-$rel-x86_64 --buildsrpm --spec elektroid.spec --sources .
mock -r fedora-$rel-x86_64 --no-clean --rebuild /var/lib/mock/fedora-$rel-x86_64/result/elektroid-*.src.rpm
```

Change `rel=35` to the version you want to build for, e.g. `rel=34` or `rel=rawhide`

**Comment by dagargo** [comment]
I've just added those lines to the `README.md` in commit a62065c89e50b7bc7b319ddac000e62b812ed33d.

**Pull request merged**
