### PR TITLE
Add man pages, german translation, and extend desktop file

### PR DESCRIPTION
**Pull request by DNS777**
* Add man pages
* Add german translation
* Add categories and keywords to the desktop file
* Dropped INSTALL symlink, copied installation help from README.MD in the INSTALL file instead

### CODE REVIEW

**Comment by DNS777** [comment]
Added man pages as well

**Comment by dagargo** [comment]
Das ist super!

I'd like to sort and squash some commits and add the needed changes in res/gui.glade so I'm merging manually. There is no need for you to do anything.

Thanks for making Elektroid great!

**Comment by DNS777** [comment]
Thx for merging and for your work on elektroid ofc!

The man pages should have .1 as file extension, because they are formatted already.

**Comment by dagargo** [comment]
While the ".man" extension seems to be right and works properly (see the [automake documentation](https://www.gnu.org/software/automake/manual/html_node/Man-Pages.html)), I've replaced it with ".1" in the fc850f01a3b6e807fde960010179e013814f5d89 commit as it's explicit and more common.

**Pull request closed without merging**
