### PR TITLE
Gate GTK package check via CLI_ONLY

### PR DESCRIPTION
**Pull request by ryanlaws**
Define CLI_ONLY conditional earlier
Use CLI_ONLY conditional for GTK package check in automake

### CODE REVIEW

**Comment by ryanlaws** [comment]
Oh nice! I just verified the `AS_IF` -> `AM_COND_IF` also works for the `autoreconf --install` and `./configure` steps, and I pushed commit 68a90df on my branch. Let me know what I can test. 

I also still want to help testing with #38 and I don't think that is blocked by anything related to this issue. However, since the latest changes to `raw_fs`, I haven't yet tested the build on my main dev machine (which has GTK).

**Comment by dagargo** [comment]
I've tested and downgraded the required version of `libsamplerate` to 0.1.8. It's really old but it works. (The resampled data is not 100% exactly the same but the number of samples matches and the file sound alike so it's a library issue or feature.)

Everything is pushed to the `raw_fs` branch already and all the tests needed in #38 can be started now.

I'll close #42 when you confirm that the `gtk` dependency error disappears.

BTW, you will no longer need either `libpulse` or `gettext` and `autopoint` in case of compiling only the CLI. Check this, please, if it works without these in case you are able to.

**Comment by dagargo** [comment]
All these errors are the same ones I was having on Debian stretch that made me downgrade the `libsamplerate` version to the one included there.

```
/home/we/src/elektroid/src/sample.c:236: undefined reference to `src_new'
```

A couple of ideas. Is the version in your system below the specified version in `configure.c`? What does the output of `./configure` say about the the library?

**Comment by ryanlaws** [comment]
So it looks like `configure.ac` wants samplerate >= 0.1.8, and the one on my system is 0.1.8-8:
```
~/src/elektroid $ sudo apt install libsamplerate-dev
Reading package lists... Done
Building dependency tree
Reading state information... Done
Note, selecting 'libsamplerate0-dev' instead of 'libsamplerate-dev'
libsamplerate0-dev is already the newest version (0.1.8-8).
The following packages were automatically installed and are no longer required:
  lua-any lua-sec lua-socket
Use 'sudo apt autoremove' to remove them.
0 upgraded, 0 newly installed, 0 to remove and 221 not upgraded.
```
I looked for "samplerate" in the output of `./configure CLI_ONLY=yes` and this line is all I saw:

```
checking for SAMPLERATE... yes
```

**Comment by dagargo** [comment]
This is part of your `make` output.

```
/bin/bash ../libtool  --tag=CC   --mode=link gcc -I../src `/usr/bin/pkg-config --cflags alsa glib-2.0 zlib`   -g -O2 `/usr/bin/pkg-config --libs alsa glib-2.0 zlib` -lsndfile   -o elektroid-cli elektroid_cli-connector.o elektroid_cli-elektroid-cli.o elektroid_cli-sample.o elektroid_cli-utils.o  -lm
libtool: link: gcc -I../src -I/usr/include/alsa -I/usr/include/glib-2.0 -I/usr/lib/arm-linux-gnueabihf/glib-2.0/include -g -O2 -o elektroid-cli elektroid_cli-connector.o elektroid_cli-elektroid-cli.o elektroid_cli-sample.o elektroid_cli-utils.o  -lasound -lglib-2.0 -lz -lsndfile -lm
```

And this is mine on my Debian stretch.

```
/bin/bash ../libtool  --tag=CC   --mode=link gcc -I../src `/usr/bin/pkg-config --cflags alsa glib-2.0 zlib`   -g -O2 `/usr/bin/pkg-config --libs alsa glib-2.0 zlib` -lsndfile -lsamplerate  -o elektroid-cli elektroid_cli-connector.o elektroid_cli-elektroid-cli.o elektroid_cli-sample.o elektroid_cli-utils.o  -lm 
libtool: link: gcc -I../src -I/usr/include/alsa -I/usr/include/glib-2.0 -I/usr/lib/x86_64-linux-gnu/glib-2.0/include -g -O2 -o elektroid-cli elektroid_cli-connector.o elektroid_cli-elektroid-cli.o elektroid_cli-sample.o elektroid_cli-utils.o  -lasound -lglib-2.0 -lz -lsndfile -lsamplerate -lm
```

The issue is that `-lsamplerate` is not included in your case and hence the linkage error but don't know why it isn't.

Could you run this?

```
$ pkg-config --libs samplerate
-lsamplerate
```

**Comment by dagargo** [comment]
Looks like `autopoint` is no longer needed and `autoreconf` doesn't complain either with this configuration.

```
$ git diff
diff --git a/configure.ac b/configure.ac
index fd7cb57..8107d31 100644
--- a/configure.ac
+++ b/configure.ac
@@ -35,8 +35,13 @@ AM_COND_IF(GUI, [PKG_CHECK_MODULES([PULSEAUDIO], [libpulse >= 5.0])])
 AC_SUBST(PULSEAUDIO_CFLAGS)
 AC_SUBST(PULSEAUDIO_LIBS)
 
-AM_COND_IF(GUI, [AM_GNU_GETTEXT([external])])
-AM_COND_IF(GUI, [AM_GNU_GETTEXT_VERSION([0.19.8])])
+AM_COND_IF(GUI, [
+AM_GNU_GETTEXT([external]),
+AM_GNU_GETTEXT_VERSION([0.12.1])
+])
 
 # Checks for header files.
 AC_CHECK_HEADERS([unistd.h limits.h zlib.h])
```

Could you try it?

**Pull request merged**
