### PR TITLE
Let autoconf set LIBS=-lm when needed and fix cross-building

### PR DESCRIPTION
**Pull request by DNS777**
This should fix builds for several architectures

### CODE REVIEW

**Comment by DNS777** [comment]
I fixed the cross building now with the debian rules instead of removing AC_FUNC_MALLOC
https://salsa.debian.org/multimedia-team/elektroid/-/blob/cb185e983d4265516637d9e8e4dce55ee96d1b09/debian/rules#L8

**Comment by DNS777** [comment]
Btw elektroid is finally in debian https://packages.debian.org/sid/elektroid
And this pull request is about to fix the most of the broken builds: https://buildd.debian.org/status/package.php?p=elektroid

**Comment by dagargo** [comment]
This is amazing news!
Thank you very much for all your efforts in porting Elektroid to Debian!

**Comment by DNS777** [comment]
yw! and thanks a lot for making this application :-)

**Pull request merged**
